### ISSUE TITLE
new ci test failures

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-phylogeny#73]
@mikerobeson, I am putting out the bat signal...

I recently migrated this repo's ci testing from Travis CI to Github Workflow. As part of that migration, we now build and test the _conda package_ for this plugin, rather than the source itself. The unit tests are currently failing:

https://github.com/qiime2/q2-phylogeny/runs/1922156894

I haven't looked to closely at this, but I suspect we are writing test data somewhere we shouldn't (and the src vs conda package change is what is revealing this issue).

If you get a chance to peek at this please let me know!

**Comment by mikerobeson** [comment]
Hi @thermokarst, I'll take a look and see what I can figure out.

**Comment by mikerobeson** [comment]
Well, upon a quick inspection, only the `raxml` tests are failing. I think the issue is this (which first appears on lines 887-889 of the error report you linked, which is essentially repeated in other test cases):

> Just in case you might need it, an alignment file with 
undetermined columns removed is printed to file /home/runner/work/q2-phylogeny/q2-phylogeny/testing/lib/python3.6/site-packages/q2_phylogeny/tests/data/aligned-dna-sequences-3.fasta.reduced
The file /home/runner/work/q2-phylogeny/q2-phylogeny/testing/lib/python3.6/site-packages/q2_phylogeny/tests/data/aligned-dna-sequences-3.fasta.reduced RAxML wants to open for writing or appending can not be opened [mode: wb], exiting ...

In a nutshell, if raxml detects identical sequences, which usually occurs after alignment filtering, then raxml will try and "reduce" the data set by removing these redundant identical sequences. It does this by writing-out a file with the suffix `.reduced` into the directory in which the original file was read in from. I am unsure why this would be an issue, but it is failing at this step and is unable to write to that path.

I do not think I have any ideas on how to handle this, as raxml will always write out this file. The only option available is to change what is written to this file (*i.e.* keep the identical sequences, but remove common gap columns with the `--print-identical-sequences` flag).

**Comment by thermokarst** [comment]
Interesting - thanks for looking into this, @mikerobeson! One thing that comes to mind is that this doesn't appear to be a problem when we run the exact same conda-package-based unit tests on busywork.qiime2.org - I'll take a look to see if there are some "gotcha" I need to remind myself of here.

**Comment by andrewsanchez** [comment]
Not sure what's up with the permissions issue on the GH runner, but we don't want our tests generating output in that directory anyways.

`tests_raxml` passes [here](https://github.com/qiime2/q2-phylogeny/runs/1939250701) (11 failures instead of 12).  Moving the input file to a temporary directory before passing it to raxml should do the trick.  If this seems like a reasonable solution, let me know and I'll do this for the other tests in #74 as well.

**Comment by thermokarst** [comment]
This is a great approach, thanks for figuring this our @andrewsanchez - I think you should go ahead and update the last test, too!
